background: pictures/background_map.png
framerate: 120
spawn_cooldown: 10
intersection:
    start: [532, 208]
    end: [858, 650]
    num_of_squares: 1024
    color: [255, 255, 255]
car:
    velocity: 5
    waypoint_clearance: 30
    sprites:
        - pictures/car1.png
        - pictures/car2.png
        - pictures/car3.png
        - pictures/car4.png
        - pictures/car5.png
    paths:
        - [[5, 64], [246, 160], [416, 253], [538, 338], [565, 390], [556, 449], [515, 525], [413, 656], [368, 751]]
        - [[4, 65], [235, 154], [353, 219], [472, 294], [576, 356], [636, 400], [704, 454], [933, 634], [1079, 751]]
        - [[2, 68], [172, 136], [303, 194], [444, 273], [556, 343], [644, 409], [710, 453], [778, 429], [906, 379], [1047, 304], [1216, 241], [1277, 227]]
        - [[1135, 751], [879, 558], [808, 489], [814, 433], [857, 401], [1042, 310], [1217, 242], [1277, 226]]
        - [[1126, 750], [1034, 684], [923, 595], [923, 595], [788, 470], [717, 407], [696, 394], [629, 406], [559, 440], [525, 499], [432, 643], [370, 751]]
        - [[1130, 751], [992, 648], [826, 509], [690, 387], [580, 305], [466, 240], [342, 182], [212, 137], [3, 50]]
        - [[1273, 157], [1176, 188], [1058, 256], [942, 323], [830, 377], [763, 397], [702, 396], [651, 364], [580, 304], [493, 256], [373, 199], [263, 153], [116, 100], [1, 50]]
        - [[1277, 153], [1166, 191], [1028, 268], [906, 341], [790, 388], [717, 394], [653, 407], [669, 432], [725, 470], [852, 560], [1062, 721], [1098, 752]]
        - [[1273, 160], [1087, 232], [939, 325], [767, 396], [672, 403], [575, 431], [523, 516], [443, 619], [392, 698], [366, 750]]
