background: pictures/background.png
framerate: 60
spawn_cooldown: 30
intersection:
    start: [350, 235]
    end: [600, 490]
    num_of_squares: 64
    color: [255, 255, 255]
car:
    velocity: 10
    waypoint_clearance: 5
    sprites:
        - pictures/car1.png
        - pictures/car2.png
        - pictures/car3.png
        - pictures/car4.png
        - pictures/car5.png
    paths:
        #- [[-20, 450], [980, 450]]
        #- [[-20, 395], [980, 395]]
        #- [[980, 330], [-50, 330]]
        #- [[980, 275], [-50, 275]]
        #- [[385, -20], [385, 780]]
        #- [[445, -20], [445, 780]]
        #- [[505, 780], [505, -50]]
        #- [[560, 780], [560, -50]]
        #- [[-20, 450], [330, 450], [350, 456], [385, 517], [385, 780]]
        #- [[-20, 395], [400, 397], [438, 441], [442, 780]]
        #- [[-20, 450], [330, 450], [338, 441], [530, 415], [565, 333], [565, -50]]

        - [[17, 453], [336, 450], [382, 463], [384, 697]]
        - [[3, 395], [335, 398], [658, 396], [954, 396]]
        - [[3, 451], [335, 447], [658, 451], [957, 452]]
        - [[14, 394], [359, 390], [436, 437], [446, 697]]
        - [[503, 718], [503, 498], [505, 185], [502, 5]]
        - [[564, 718], [562, 498], [563, 182], [565, 6]]
        - [[505, 698], [504, 422], [433, 334], [5, 332]]
        - [[565, 698], [557, 363], [473, 272], [5, 273]]
        - [[566, 698], [565, 494], [609, 453], [957, 454]]
        - [[508, 699], [508, 461], [537, 402], [625, 395], [956, 395]]
        - [[385, 5], [385, 227], [384, 550], [385, 718]]
        - [[446, 5], [445, 228], [446, 547], [448, 719]]
        - [[385, 4], [387, 233], [358, 279], [3, 272]]
        - [[444, 5], [441, 237], [424, 315], [376, 328], [2, 330]]
        - [[442, 6], [439, 241], [459, 311], [512, 358], [587, 394], [957, 396]]
        - [[384, 4], [387, 242], [428, 357], [519, 431], [611, 454], [958, 453]]
        - [[955, 332], [611, 332], [291, 331], [4, 329]]
        - [[958, 279], [614, 281], [298, 275], [5, 276]]
        - [[958, 334], [629, 333], [511, 288], [504, 225], [506, 4]]
        - [[958, 276], [632, 275], [586, 273], [563, 234], [561, 3]]
        - [[957, 330], [620, 330], [498, 354], [444, 421], [440, 522], [442, 697]]
        - [[959, 274], [631, 276], [530, 293], [450, 329], [395, 381], [384, 482], [383, 700]]

