background: pictures/background.png
framerate: 60
spawn_cooldown: 30
intersection:
    start: [350, 235]
    end: [600, 490]
    num_of_squares: 64
    color: [255, 255, 255]
car:
    velocity: 10
    waypoint_clearance: 5
    sprites:
        - pictures/car1.png
        - pictures/car2.png
        - pictures/car3.png
        - pictures/car4.png
        - pictures/car5.png
    paths:
        #- [[-20, 450], [980, 450]]
        #- [[-20, 395], [980, 395]]
        #- [[980, 330], [-50, 330]]
        #- [[980, 275], [-50, 275]]
        #- [[385, -20], [385, 780]]
        #- [[445, -20], [445, 780]]
        #- [[505, 780], [505, -50]]
        #- [[560, 780], [560, -50]]
        #- [[-20, 450], [330, 450], [350, 456], [385, 517], [385, 780]]
        #- [[-20, 395], [400, 397], [438, 441], [442, 780]]
        #- [[-20, 450], [330, 450], [338, 441], [530, 415], [565, 333], [565, -50]]

        #- [[17, 453], [336, 450], [382, 463], [384, 697]]
        #- [[3, 395], [365, 398], [658, 396], [954, 396]]
        #- [[3, 451], [365, 447], [658, 451], [957, 452]]
        #- [[14, 394], [359, 390], [436, 437], [446, 697]]
        #- [[503, 718], [503, 468], [505, 185], [502, 5]]
        #- [[564, 718], [562, 468], [563, 182], [565, 6]]
        #- [[505, 698], [504, 422], [433, 334], [5, 332]]
        #- [[565, 698], [557, 363], [473, 272], [5, 273]]
        #- [[566, 698], [565, 494], [609, 453], [957, 454]]
        #- [[508, 699], [508, 461], [537, 402], [625, 395], [956, 395]]
        #- [[385, 5], [385, 247], [384, 550], [385, 718]]
        #- [[446, 5], [445, 248], [446, 547], [448, 719]]
        #- [[385, 4], [387, 233], [358, 279], [3, 272]]
        #- [[444, 5], [441, 237], [424, 315], [376, 328], [2, 330]]
        #- [[442, 6], [439, 241], [459, 311], [512, 358], [587, 394], [957, 396]]
        #- [[384, 4], [387, 242], [428, 357], [519, 431], [611, 454], [958, 453]]
        #- [[955, 332], [590, 332], [291, 331], [4, 329]]
        #- [[958, 279], [590, 281], [298, 275], [5, 276]]
        #- [[958, 334], [629, 333], [511, 288], [504, 225], [506, 4]]
        #- [[958, 276], [632, 275], [586, 273], [563, 234], [561, 3]]
        #- [[957, 330], [620, 330], [498, 354], [444, 421], [440, 522], [442, 697]]
        #- [[959, 274], [631, 276], [530, 293], [450, 329], [395, 381], [384, 482], [383, 700]]

        - [[3, 395], [365, 398], [658, 396], [954, 396]]
        - [[3, 451], [365, 447], [658, 451], [957, 452]]
        - [[958, 279], [590, 281], [298, 275], [5, 276]]
        - [[955, 332], [590, 332], [291, 331], [4, 329]]
        - [[564, 718], [562, 468], [563, 182], [565, 6]]
        - [[503, 718], [503, 468], [505, 185], [502, 5]]
        - [[446, 5], [445, 248], [446, 547], [448, 719]]
        - [[385, 5], [385, 247], [384, 550], [385, 718]]
        - [[5, 394], [370, 391], [624, 391], [952, 392]]
        - [[7, 394], [366, 391], [414, 397], [438, 433], [439, 475], [437, 503], [442, 717]]
        - [[5, 394], [364, 396], [437, 397], [490, 368], [509, 329], [506, 245], [503, 215], [505, 6]]
        - [[5, 448], [368, 441], [586, 449], [619, 448], [956, 451]]
        - [[6, 452], [363, 444], [392, 449], [385, 474], [383, 504], [385, 715]]
        - [[8, 457], [368, 453], [464, 439], [510, 407], [553, 358], [564, 295], [563, 244], [562, 215], [564, 7]]
        - [[504, 717], [506, 473], [505, 246], [504, 216], [507, 5]]
        - [[504, 716], [507, 471], [515, 420], [547, 401], [586, 393], [616, 392], [956, 394]]
        - [[505, 717], [506, 471], [494, 415], [473, 365], [438, 342], [392, 330], [362, 330], [336, 331], [3, 332]]
        - [[562, 719], [561, 473], [560, 247], [560, 220], [566, 7]]
        - [[563, 718], [561, 477], [570, 451], [591, 446], [607, 443], [956, 449]]
        - [[562, 718], [560, 473], [540, 402], [506, 337], [457, 280], [402, 271], [361, 269], [342, 273], [5, 275]]
        - [[958, 337], [582, 334], [362, 330], [336, 331], [4, 331]]
        - [[955, 334], [586, 332], [534, 338], [487, 360], [457, 389], [442, 418], [441, 479], [440, 498], [444, 715]]
        - [[957, 336], [587, 334], [546, 329], [523, 306], [504, 275], [499, 242], [499, 222], [504, 7]]
        - [[956, 276], [584, 278], [357, 276], [340, 275], [5, 272]]
        - [[955, 274], [586, 277], [538, 282], [487, 298], [449, 322], [415, 357], [389, 391], [384, 431], [381, 475], [380, 501], [385, 716]]
        - [[954, 279], [588, 278], [568, 257], [565, 242], [564, 225], [563, 6]]
        - [[446, 7], [443, 249], [445, 478], [446, 503], [443, 716]]
        - [[441, 11], [437, 247], [440, 295], [453, 336], [480, 368], [522, 384], [560, 391], [589, 393], [608, 391], [952, 396]]
        - [[440, 10], [447, 249], [439, 287], [415, 315], [391, 333], [364, 334], [340, 331], [6, 333]]
        - [[385, 8], [386, 245], [384, 479], [382, 500], [385, 715]]
        - [[381, 8], [388, 248], [395, 302], [413, 354], [441, 399], [469, 442], [520, 454], [584, 456], [610, 453], [953, 459]]
        - [[385, 9], [389, 245], [383, 260], [366, 267], [339, 269], [4, 275]]

